//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reminder_notes_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_reminder_appEntities : DbContext
    {
        public db_reminder_appEntities()
            : base("name=db_reminder_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<note_category> note_category { get; set; }
        public virtual DbSet<notes> notes { get; set; }
        public virtual DbSet<reminder_category> reminder_category { get; set; }
        public virtual DbSet<reminders> reminders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
