//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reminder_notes_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class notes
    {
        public int id { get; set; }
        public int id_category { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> last_edited { get; set; }
    
        public virtual note_category note_category { get; set; }
    }
}
