//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reminder_notes_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class note_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public note_category()
        {
            this.notes = new HashSet<notes>();
        }
        public note_category(int _id, string _name)
        {
            id = _id;
            name = _name;
        }
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notes> notes { get; set; }
    }
}
