//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reminder_notes_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminders
    {
        public int id { get; set; }
        public Nullable<int> id_category { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual reminder_category reminder_category { get; set; }
    }
}
